- hosts: webservers

  tasks:
    - name: install git
      # apt-get update && apt-get install git
      ansible.builtin.apt: # имя модуля Ansible
        name: git
        state: present
        update_cache: yes
      tags: [install, config]

    - name: rm git
      # apt-get remove git
      ansible.builtin.apt:
        name: git
        state: absent
      tags: [uninstall]
