- hosts: servers

  vars:
    users:
      - jaime
      - sansa
      - robert
      - arya
    admin_group: admin

  tasks:
    - ansible.builtin.import_tasks: tasks-install-common.yml
      tags: install

    - ansible.builtin.import_tasks: tasks-install-node.yml
      tags: [install, install-node]

    - ansible.builtin.import_tasks: tasks-uninstall-node.yml
      tags: uninstall-node

    - name: Add users
      ansible.builtin.user:
        name: "{{ item }}"
        groups: "{{ admin_group }}"
      loop: "{{ users }}"
      tags: [install, setup-users]

    - name: Add users ssh keys
      ansible.posix.authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('ansible.builtin.file', './files/id_do_rsa.pub') }}"
      loop: "{{ users }}"
      tags: [install, setup-users]

    - name: Add users to sudoeers and validate
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%{{ admin_group }}'
        line: '%{{ admin_group }} ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
      tags: install

    - name: Add gitconfig for users
      ansible.builtin.template:
        src: templates/gitconfig.j2
        dest: '/home/{{ user }}/.gitconfig'
        owner: '{{ user }}'
      loop: "{{ users }}"
      loop_control:
        loop_var: user
      tags: [install, setup-users]
