- hosts: servers
  gather_facts: no

  vars:
    nginx_port: 80
    root_dir: /var/tmp/www

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes
      tags: install

    - name: create the root dir if it does not exist
      file:
        path: "{{ root_dir }}"
        state: directory
        mode: '0777'
      tags: [install, update-content]

    - name: set or update content
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{ root_dir }}/index.html"
      become: yes
      tags: [install, update-content]

    - name: set or update nginx config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes
      tags: [install, update-config]

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      become: yes
