- name: Add nodejs apt key
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add nodejs 18.x ppa for apt repo
  ansible.builtin.apt_repository:
    repo: deb https://deb.nodesource.com/node_18.x focal main
    update_cache: yes

# https://askubuntu.com/questions/1414803/im-getting-errors-that-i-dont-understand-installing-nodejs-on-a-freshly-instal
- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: Install node
  ansible.builtin.apt:
    update_cache: yes
    name: nodejs
    state: present
